accessModes: ReadWriteMany
configMap:
  name: isc
image: registry.access.redhat.com/ubi9/ubi:latest
namespace: default
persistentVolumeClaim:
  name: mirror-pvc
storage: 1000Gi
storageClassName: ocs-storagecluster-cephfs
volumeMode: Filesystem
