accessModes: ReadWriteOnce
baseURL: https://mirror.openshift.com/pub/openshift-v4
binary: oc-mirror
cache: /mirror
configMap:
  key: ImageSetConfiguration
  name: isc
file: ocp
image: registry.access.redhat.com/ubi9/ubi:latest
imagePullSecret:
  redhat: pull-secret
  mirror: pull-secret-mirror-quay
job:
  name: disk2mirror
mirrorURL: mirror-quay.internal.apps.hub.sebastian-colomar.com/mirror
namespace: default
persistentVolumeClaim:
  name: mirror-pvc
release: 4.20.10
storage: 1000Gi
storageClassName: ocs-storagecluster-ceph-rbd
volumeMode: Filesystem
workingDir: /mirror
