apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- ACM/Role.yaml
  #- ACM/RoleBinding.yaml
  - apps/storage4mirror2disk.yaml
  #- apps/mirror2disk.yaml
  - apps/disk2mirror.yaml
